<?php

class Mage {
  public static function throwException($msg) {
    die($msg);
  }
}

require "varnish.php";
$varnish = new Nexcessnet_Turpentine_Model_Varnish_Admin_Socket(array(
	"host" => "varnish",
	"auth_secret" => file_get_contents("/varnish.secret")
));

$vcl = $varnish->vcl_show("boot");
if ($vcl["code"] == Nexcessnet_Turpentine_Model_Varnish_Admin_Socket::CODE_OK) {
  $vcl = $vcl["text"];
  $vcl = preg_replace("/#AUTOGENERATED_START.*#AUTOGENERATED_END/ms", "#AUTOGENERATED_START\n#AUTOGENERATED_END", $vcl);
  $vcl = explode("\n", $vcl);
  $apaches = array();
  $hosts = file("/etc/hosts");
  foreach ($hosts as $host) {
    $host = explode("\t", $host);
    if (strpos($host[1], "apache_") !== 0) continue;
    $hostname = explode(" ", $host[1])[0];
    $apaches[$hostname] = $host[0];
  }
  ksort($apaches);

  if (sizeof ($apaches) > 1) {
    $hosts_to_add_to_vcl = "";
    foreach ($apaches as $name=>$ip) {
      $hosts_to_add_to_vcl .= "backend $name {\n\t.host = \"$ip\";\n\t.port = \"80\";\n}\n";
    }

    $hosts_to_add_to_vcl .= "sub vcl_init {\n\tnew cluster1 = directors.round_robin();\n";
    foreach ($apaches as $name=>$ip) {
      $hosts_to_add_to_vcl .= "\tcluster1.add_backend($name);\n";
    }
    $hosts_to_add_to_vcl .= "}\n";
    $hosts_to_add_to_vcl .= "sub vcl_recv {set req.backend_hint = tcluster1.backend();}\n";
  }

  $new_vcl = "";
  foreach ($vcl as $line) {
    $new_vcl .= "$line\n";
    if ($line == "#AUTOGENERATED_START") {
      $new_vcl .= $hosts_to_add_to_vcl;
    }
  }

  $vcl_name = "autogenated" . time();
  $varnish->vcl_inline($vcl_name, $new_vcl);
  sleep(1);
  $varnish->vcl_use($vcl_name);
}
